const rooms = new Map();
const words = [
  "apple","banana","orange","grape","watermelon","pineapple","strawberry","cherry","mango","lemon",
  "cat","dog","elephant","tiger","lion","giraffe","monkey","bear","wolf","rabbit",
  "house","tree","car","bicycle","bus","train","airplane","boat","motorcycle","truck",
  "chair","table","bed","sofa","lamp","door","window","cup","plate","knife",
  "pizza","burger","sandwich","pasta","ice cream","cake","bread","hotdog","fries","soup",
  "sun","moon","star","cloud","rain","snow","mountain","river","ocean","beach",
  "hat","shirt","pants","shoes","dress","jacket","scarf","glasses","watch","belt",
  "ball","bat","racket","frisbee","kite","skateboard","scooter","helmet","gloves","net",
  "phone","computer","laptop","tablet","camera","headphones","television","remote","printer","speaker",
  "clock","calendar","book","pen","pencil","notebook","backpack","eraser","marker","paintbrush",
  "bridge","road","street","traffic light","sign","train station","airport","park","garden","fountain",
  "bee","butterfly","ant","spider","snail","fish","crab","octopus","shark","whale",
  "cupcake","donut","chocolate","candy","popcorn","cookie","muffin","pie","soda","milkshake",
  "football","soccer ball","basketball","tennis ball","volleyball","hockey stick","golf club","skis","sled","surfboard",
  "air balloon","rocket","helicopter","submarine","yacht","canoe","ferry","truck","van","ambulance",
  "microwave","refrigerator","oven","toaster","blender","kettle","coffee machine","washing machine","fan","heater",
  "key","lock","wallet","bag","umbrella","ring","necklace","bracelet","hat","gloves",
  "piano","guitar","violin","drums","trumpet","flute","saxophone","microphone","speaker","organ",
  "train track","railway","bus stop","crosswalk","tunnel","airport runway","ferry dock","lighthouse","tower","stadium",
  "cloud","rainbow","storm","thunder","lightning","fog","hail","wind","snowflake","icicle",
  "camera","tripod","lens","flash","film","video camera","drone","selfie stick","memory card","battery",
  "apple tree","oak tree","pine tree","cactus","bush","flower","rose","sunflower","tulip","lily",
  "doghouse","cat tree","birdcage","fish tank","hamster wheel","swing","slide","sandbox","treehouse","trampoline",
  "globe","map","compass","binoculars","magnifying glass","telescope","satellite","rocket","spaceship","planet",
  "birthday cake","candles","balloons","gift","party hat","streamers","confetti","pinata","party horn","party popper",
  "trophy","medal","ribbon","certificate","scoreboard","podium","flag","banner","champion belt","laurel wreath",
  "cloud","mountain","volcano","river","waterfall","lake","island","cave","desert","forest",
  "diamond","gold","silver","bronze","pearl","gem","jewel","ring","necklace","crown",
  "hand","foot","eye","ear","nose","mouth","hair","finger","toe","shoulder",
  "train","bus","car","bicycle","motorbike","scooter","truck","van","airplane","boat",
  "coffee","tea","juice","milk","water","soda","smoothie","hot chocolate","beer","wine",
  "tiger","lion","cheetah","leopard","panther","jaguar","cougar","hyena","fox","wolf",
  "sunglasses","hat","scarf","gloves","jacket","coat","boots","shoes","watch","belt",
  "computer","laptop","tablet","smartphone","keyboard","mouse","printer","router","camera","microphone",
  "pizza","burger","hotdog","fries","sandwich","pasta","soup","salad","steak","sushi",
  "house","apartment","cottage","villa","castle","skyscraper","tent","treehouse","hut","barn",
  "rain","snow","sun","moon","cloud","storm","fog","lightning","thunder","wind",
  "guitar","piano","drums","violin","flute","trumpet","saxophone","microphone","harp","cello",
  "dog","cat","rabbit","hamster","parrot","goldfish","turtle","snake","lizard","horse",
  "beach","mountain","forest","river","lake","desert","island","cave","waterfall","volcano",
  "train","bus","car","bicycle","motorbike","scooter","truck","van","airplane","boat",
  "apple","banana","orange","grape","watermelon","pineapple","strawberry","cherry","mango","lemon",
  "ball","bat","racket","frisbee","kite","skateboard","scooter","helmet","gloves","net","goal",
  "chocolate","candy","cookie","cake","ice cream","donut","popcorn","muffin","brownie","pie",
  "sofa","chair","bed","table","lamp","shelf","cabinet","desk","mirror","curtain","rug",
  "clock","watch","calendar","alarm","thermometer","barometer","compass","scale","map","globe",
  "sun","moon","star","cloud","rain","snow","wind","fog","thunder","lightning","rainbow",
  "train","bus","car","bicycle","motorbike","scooter","truck","van","airplane","boat",
  "piano","guitar","violin","drums","trumpet","flute","saxophone","microphone","harp","cello",
  "dog","cat","rabbit","hamster","parrot","goldfish","turtle","snake","lizard","horse",
  "pizza","burger","hotdog","fries","sandwich","pasta","soup","salad","steak","sushi",
  "house","apartment","cottage","villa","castle","skyscraper","tent","treehouse","hut","barn",
  "apple tree","oak tree","pine tree","cactus","bush","flower","rose","sunflower","tulip","lily",
  "birthday cake","candles","balloons","gift","party hat","streamers","confetti","pinata","party horn",
  "diamond","gold","silver","bronze","pearl","gem","jewel","ring","necklace","crown","tiara",
  "eye","ear","nose","mouth","hand","foot","finger","toe","shoulder","elbow","knee","back","neck",
  "soccer ball","basketball","football","tennis ball","volleyball","hockey stick","golf club","ski","sled","surfboard",
  "coffee","tea","juice","milk","water","soda","smoothie","hot chocolate","beer","wine","cocktail","lemonade",
  "rocket","spaceship","drone","satellite","planet","moon","comet","star","asteroid","telescope","astronaut",
  "umbrella","raincoat","boots","sunglasses","hat","scarf","gloves","jacket","coat","shorts","shirt","dress",
  "train station","bus stop","airport","ferry dock","lighthouse","bridge","road","street","traffic light","sign",
  "fountain","garden","park","playground","swimming pool","gym","stadium","theater","cinema","library",
  "hammer","screwdriver","wrench","drill","saw","pliers","nail","screw","paintbrush","ladder",
  "camera","tripod","lens","flash","film","video camera","drone","selfie stick","memory card","battery",
  "key","lock","wallet","bag","ring","necklace","bracelet","gloves","hat","shoes",
  "cloud","mountain","volcano","river","waterfall","lake","island","cave","desert","forest",
  "trophy","medal","ribbon","certificate","scoreboard","podium","flag","banner","champion belt","laurel wreath"
];

export {rooms,words};